BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        id: main_box
    Label:
        size_hint_y: 0.1
        text: app.status_text
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Label:
            text: 'Create Widgets'
            on_text: app.create_label()
        Label:
            text: 'Clear Widgets'
            on_text: app.clear_all()